# Generated by Django 6.0.4 on 2026-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
