# Generated by Django 6.0.4 on 2026-05-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('length_cm', models.SmallIntegerField()),
                ('width_cm', models.SmallIntegerField()),
                ('height_cm', models.SmallIntegerField()),
                ('material', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='terrarium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.terrarium'),
        ),
        migrations.CreateModel(
            name='TerrariumCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='terrarium',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.terrariumcategory'),
        ),
        migrations.CreateModel(
            name='TerrariumImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('terrarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.terrarium')),
            ],
        ),
    ]
