# Generated by Django 6.0.4 on 2026-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные')], default='card', max_length=10),
        ),
    ]
