import img1 from '../../assets/images/1.png';
import img2 from '../../assets/images/2.png';
import img3 from '../../assets/images/3.png';
import img4 from '../../assets/images/4.png';

export const SNAKES = [
  {
    id: 1,
    image: img1,
    available: true,
    name: 'Маисовый полоз',
    lengthMin: 90,
    lengthMax: 150,
    tempMin: 24,
    tempMax: 28,
    colors: 12,
    skill: 1,
    skillLabel: 'Начинающий',
    description:
      'Идеальная змея для начинающих. Спокойный характер, яркая окраска, неприхотлива в уходе. Большой выбор морф.',
    price: 15000,
    badge: { label: 'Хит продаж', bg: 'rgba(180,255,199,0.4)', border: '#00c530', color: '#00c530' },
  },
  {
    id: 2,
    image: img2,
    available: true,
    name: 'Королевская змея',
    lengthMin: 100,
    lengthMax: 180,
    tempMin: 22,
    tempMax: 28,
    colors: 6,
    skill: 2,
    skillLabel: 'Средний',
    description:
      'Контрастный окрас, активный характер. Легко адаптируется к террариуму, выносливая и любознательная.',
    price: 22000,
    badge: { label: 'Новинка', bg: 'rgba(180,255,240,0.4)', border: '#00c58d', color: '#00c597' },
  },
  {
    id: 3,
    image: img3,
    available: false,
    name: 'Императорский удав',
    lengthMin: 180,
    lengthMax: 300,
    tempMin: 26,
    tempMax: 32,
    colors: 4,
    skill: 3,
    skillLabel: 'Эксперт',
    description:
      'Крупная, мощная и спокойная змея с выразительным узором. Подходит опытным владельцам. Живёт десятилетиями.',
    price: 85000,
    badge: null,
  },
  {
    id: 4,
    image: img4,
    available: true,
    name: 'Шаровый питон',
    lengthMin: 100,
    lengthMax: 150,
    tempMin: 27,
    tempMax: 32,
    colors: 20,
    skill: 2,
    skillLabel: 'Средний',
    description:
      'Невысокая активность, компактные размеры и огромное количество морф. Спокойный темперамент, сворачивается в шар при стрессе.',
    price: 35000,
    badge: { label: 'Ограниченно', bg: 'rgba(255,220,180,0.4)', border: '#c56300', color: '#c56300' },
  },
  {
    id: 5,
    image: img1,
    available: true,
    name: 'Молочная змея',
    lengthMin: 60,
    lengthMax: 120,
    tempMin: 22,
    tempMax: 27,
    colors: 8,
    skill: 1,
    skillLabel: 'Начинающий',
    description:
      'Яркая трёхцветная окраска под коралловую змею. Абсолютно безопасна, активна в ночное время, легка в уходе.',
    price: 18000,
    badge: null,
  },
  {
    id: 6,
    image: img2,
    available: false,
    name: 'Сетчатый питон',
    lengthMin: 300,
    lengthMax: 700,
    tempMin: 28,
    tempMax: 34,
    colors: 3,
    skill: 3,
    skillLabel: 'Эксперт',
    description:
      'Одна из самых длинных змей в мире. Требует большого террариума и опыта содержания. Для настоящих ценителей.',
    price: 120000,
    badge: { label: 'Редкий', bg: 'rgba(220,180,255,0.4)', border: '#9b30c5', color: '#9b30c5' },
  },
];
